### PR TITLE
[WIP] Update react-native to 0.60.4

### PR DESCRIPTION
**Pull request by irgendeinich**
# Details

This makes the necessary changes for our Catalog app and react-native wrapper to work with react-native `0.60.4`. 

Android and iOS was updated to work with the latest version, Windows support was removed and the changelog mentions that you should use the previous version.

I made this bump the version to `1.25.0`.

# Acceptance Criteria

- [ ] When approved, right before merging, rebase with master and increment the package version in `package.json`, `package-lock.json`, and `samples/Catalog/package.json` (see example commit:  https://github.com/PSPDFKit/react-native/pull/202/commits/1bf805feef2ac268743e4905d94d6d8c8f16ec59).
- [ ] Create a new release (and tag) with the new package version (see https://github.com/PSPDFKit/react-native/releases).

### CODE REVIEW

**Comment by leoek** [comment]
Please reconsider removing Windows support. It would be much nicer to keep the IOS/Android only stuff on a separate Branch (maybe "next") and merge master into that one if new features are added.

With this approach you could offer compatibility with RN 60 and keep the feature set of Windows/IOS/Android as close as possible.

**Comment by leoek** [comment]
Also this situation shouldn't be too long anyways as rn-windows should have RN 60 support before the end of 2019.

**Comment by steipete** [comment]
Most customers use iOS+Android, only a tiny fraction uses UWP. It makes sense as a business to optimize for the majority. I am frustrated as well about the state of React Native + UWP, but at least Microsoft has a plan for that, and it's a temporary issue.

**Comment by leoek** [comment]
I understand that, however I feel like dropping Windows Support will split the Windows and Android/IOS version further apart. As this is a temporary issue the API consistency should not worsen during this time period.

If you want to have the newest version on your default/master branch, consider making a stable branch which contains the version which has support for all three platforms. This ensures that the Windows Version wont lack behind too much.

Also you should consider that Windows supports RN 0.59 now. Most libraries support a range of RN versions and it is not exactly clear to me, why you only want to support one. It does not seem like pspdfkit uses features RN 60 feature which are not in RN 0.59.

>Most customers use iOS+Android
90% or more of these customers are probably not always on the latest react-native version (because of the fast rn development and other libraries which do not support the newest rn version yet). Only supporting the newest version will make it hard for them to upgrade to a new react-native-pspdfkit version.

**Comment by steipete** [comment]
Thanks for your input! Our approach is that master always supports the latest stable version of the wrappers, we do that consistently across Xamarin, Appcelerator, Cordova, React Native and Flutter. We'll keep a branch for the UWP work until we can unify that again.

If we ever change this is a much larger discussion which needs to be adopted across 6+ repos. So far, our current approach didn't cause complains.

**Pull request merged**
