### PR TITLE
Proposal for specific peer Dependencies

### LINKED ISSUE #174: Add specific peer Dependencies
Currently the peerDependencies dont reference a version, however certain releases of the wrapper require certain react-native versions. These should be specified.

### PR DESCRIPTION
**Pull request by leoek**
This adds specific peer Dependencies and therefore fixes #174

Also I would like a version update to mitigate #173 (Currently this PR does not change the version)

Are you fine with PRs which increment the patch version? The resolved package seems to be inconsistent if it's exactly the same version. (This seems to be a yarn or github issue, because the lock file should prevent this.)

### CODE REVIEW

**Comment by nickwinder** [comment]
Please HOLD until CLA is signed.

**Comment by leoek** [comment]
@nickwinder CLA is signed

**Comment by nickwinder** [comment]
Sadly this is not going to be possible @leoek. 

iOS and Android now support `react-native` 0.59.*. Windows is unable to guarantee this because `react-native-windows` has fallen behind with the RC being `0.57.0-rc5`. I see no signs that 0.59 support is coming soon and we may have to wait for subsequent versions. 

So with this being said, we cannot limit the peer dependencies as this PR denotes. `react-native` `0.*.*` would be possible but rather meaningless.

**Comment by leoek** [comment]
@nickwinder This isn't an issue if we define a range for the versions of the peerdependencies.

Please review my latest change to this PR

**Pull request merged**
